name: CI

on: push

jobs:
  build-test-go:
    runs-on: ubuntu-latest
#    env:
#      GOPRIVATE: github.com/climacell/*
#      GH_ACCESS_TOKEN: ${{ secrets.ORG_AUTH_TOKEN }}
#      GOFLAGS: "-mod=mod"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

#      - name: update Github Token
#        run: |
#          git config --global url."https://$GH_ACCESS_TOKEN@github.com/".insteadOf "https://github.com/"
#        shell: bash

      - name: Build And Test Go
        uses: climacell/cicd-shared-libraries/workflows/go-build-test@v0.0.22
        with:
          go_version: 1.19.0


  go-publish:
    name: Publish Go Release
    runs-on: ubuntu-latest
    needs: build-test-go
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version and push tag
        id: tag-version-with-prefix
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
          release_branches: main
          commit_sha: ${{ github.sha }}
      - run: echo ${{ steps.tag-version-with-prefix.outputs.new_tag }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-version-with-prefix.outputs.new_tag }}
          release_name: Release ${{ steps.tag-version-with-prefix.outputs.new_tag }}
          draft: false
          prerelease: false
          body: ${{ steps.tag-version-with-prefix.outputs.changelog }}